# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liaolinwei/mesosFwk/mapreduce-lite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liaolinwei/mesosFwk/mapreduce-lite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liaolinwei/mesosFwk/mapreduce-lite/CMakeFiles /home/liaolinwei/mesosFwk/mapreduce-lite/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liaolinwei/mesosFwk/mapreduce-lite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named varint32_test

# Build rule for target.
varint32_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 varint32_test
.PHONY : varint32_test

# fast build rule for target.
varint32_test/fast:
	$(MAKE) -f src/base/CMakeFiles/varint32_test.dir/build.make src/base/CMakeFiles/varint32_test.dir/build
.PHONY : varint32_test/fast

#=============================================================================
# Target rules for targets named base

# Build rule for target.
base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 base
.PHONY : base

# fast build rule for target.
base/fast:
	$(MAKE) -f src/base/CMakeFiles/base.dir/build.make src/base/CMakeFiles/base.dir/build
.PHONY : base/fast

#=============================================================================
# Target rules for targets named class_register_test

# Build rule for target.
class_register_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 class_register_test
.PHONY : class_register_test

# fast build rule for target.
class_register_test/fast:
	$(MAKE) -f src/base/CMakeFiles/class_register_test.dir/build.make src/base/CMakeFiles/class_register_test.dir/build
.PHONY : class_register_test/fast

#=============================================================================
# Target rules for targets named stl-util_test

# Build rule for target.
stl-util_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stl-util_test
.PHONY : stl-util_test

# fast build rule for target.
stl-util_test/fast:
	$(MAKE) -f src/base/CMakeFiles/stl-util_test.dir/build.make src/base/CMakeFiles/stl-util_test.dir/build
.PHONY : stl-util_test/fast

#=============================================================================
# Target rules for targets named cvector_test

# Build rule for target.
cvector_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cvector_test
.PHONY : cvector_test

# fast build rule for target.
cvector_test/fast:
	$(MAKE) -f src/base/CMakeFiles/cvector_test.dir/build.make src/base/CMakeFiles/cvector_test.dir/build
.PHONY : cvector_test/fast

#=============================================================================
# Target rules for targets named strutil

# Build rule for target.
strutil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strutil
.PHONY : strutil

# fast build rule for target.
strutil/fast:
	$(MAKE) -f src/strutil/CMakeFiles/strutil.dir/build.make src/strutil/CMakeFiles/strutil.dir/build
.PHONY : strutil/fast

#=============================================================================
# Target rules for targets named split_string_test

# Build rule for target.
split_string_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 split_string_test
.PHONY : split_string_test

# fast build rule for target.
split_string_test/fast:
	$(MAKE) -f src/strutil/CMakeFiles/split_string_test.dir/build.make src/strutil/CMakeFiles/split_string_test.dir/build
.PHONY : split_string_test/fast

#=============================================================================
# Target rules for targets named strcodec_test

# Build rule for target.
strcodec_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 strcodec_test
.PHONY : strcodec_test

# fast build rule for target.
strcodec_test/fast:
	$(MAKE) -f src/strutil/CMakeFiles/strcodec_test.dir/build.make src/strutil/CMakeFiles/strcodec_test.dir/build
.PHONY : strcodec_test/fast

#=============================================================================
# Target rules for targets named join_strings_test

# Build rule for target.
join_strings_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 join_strings_test
.PHONY : join_strings_test

# fast build rule for target.
join_strings_test/fast:
	$(MAKE) -f src/strutil/CMakeFiles/join_strings_test.dir/build.make src/strutil/CMakeFiles/join_strings_test.dir/build
.PHONY : join_strings_test/fast

#=============================================================================
# Target rules for targets named stringprintf_test

# Build rule for target.
stringprintf_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stringprintf_test
.PHONY : stringprintf_test

# fast build rule for target.
stringprintf_test/fast:
	$(MAKE) -f src/strutil/CMakeFiles/stringprintf_test.dir/build.make src/strutil/CMakeFiles/stringprintf_test.dir/build
.PHONY : stringprintf_test/fast

#=============================================================================
# Target rules for targets named hash

# Build rule for target.
hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash
.PHONY : hash

# fast build rule for target.
hash/fast:
	$(MAKE) -f src/hash/CMakeFiles/hash.dir/build.make src/hash/CMakeFiles/hash.dir/build
.PHONY : hash/fast

#=============================================================================
# Target rules for targets named md5_hash_test

# Build rule for target.
md5_hash_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 md5_hash_test
.PHONY : md5_hash_test

# fast build rule for target.
md5_hash_test/fast:
	$(MAKE) -f src/hash/CMakeFiles/md5_hash_test.dir/build.make src/hash/CMakeFiles/md5_hash_test.dir/build
.PHONY : md5_hash_test/fast

#=============================================================================
# Target rules for targets named system

# Build rule for target.
system: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 system
.PHONY : system

# fast build rule for target.
system/fast:
	$(MAKE) -f src/system/CMakeFiles/system.dir/build.make src/system/CMakeFiles/system.dir/build
.PHONY : system/fast

#=============================================================================
# Target rules for targets named condition_variable_test

# Build rule for target.
condition_variable_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 condition_variable_test
.PHONY : condition_variable_test

# fast build rule for target.
condition_variable_test/fast:
	$(MAKE) -f src/system/CMakeFiles/condition_variable_test.dir/build.make src/system/CMakeFiles/condition_variable_test.dir/build
.PHONY : condition_variable_test/fast

#=============================================================================
# Target rules for targets named mutex_test

# Build rule for target.
mutex_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mutex_test
.PHONY : mutex_test

# fast build rule for target.
mutex_test/fast:
	$(MAKE) -f src/system/CMakeFiles/mutex_test.dir/build.make src/system/CMakeFiles/mutex_test.dir/build
.PHONY : mutex_test/fast

#=============================================================================
# Target rules for targets named filepattern_test

# Build rule for target.
filepattern_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filepattern_test
.PHONY : filepattern_test

# fast build rule for target.
filepattern_test/fast:
	$(MAKE) -f src/system/CMakeFiles/filepattern_test.dir/build.make src/system/CMakeFiles/filepattern_test.dir/build
.PHONY : filepattern_test/fast

#=============================================================================
# Target rules for targets named sorted_buffer_test

# Build rule for target.
sorted_buffer_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sorted_buffer_test
.PHONY : sorted_buffer_test

# fast build rule for target.
sorted_buffer_test/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/sorted_buffer_test.dir/build.make src/sorted_buffer/CMakeFiles/sorted_buffer_test.dir/build
.PHONY : sorted_buffer_test/fast

#=============================================================================
# Target rules for targets named memory_allocator_test

# Build rule for target.
memory_allocator_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memory_allocator_test
.PHONY : memory_allocator_test

# fast build rule for target.
memory_allocator_test/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/memory_allocator_test.dir/build.make src/sorted_buffer/CMakeFiles/memory_allocator_test.dir/build
.PHONY : memory_allocator_test/fast

#=============================================================================
# Target rules for targets named memory_piece_test

# Build rule for target.
memory_piece_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memory_piece_test
.PHONY : memory_piece_test

# fast build rule for target.
memory_piece_test/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/memory_piece_test.dir/build.make src/sorted_buffer/CMakeFiles/memory_piece_test.dir/build
.PHONY : memory_piece_test/fast

#=============================================================================
# Target rules for targets named memory_piece_less_than_test

# Build rule for target.
memory_piece_less_than_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memory_piece_less_than_test
.PHONY : memory_piece_less_than_test

# fast build rule for target.
memory_piece_less_than_test/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/memory_piece_less_than_test.dir/build.make src/sorted_buffer/CMakeFiles/memory_piece_less_than_test.dir/build
.PHONY : memory_piece_less_than_test/fast

#=============================================================================
# Target rules for targets named memory_piece_io_test

# Build rule for target.
memory_piece_io_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memory_piece_io_test
.PHONY : memory_piece_io_test

# fast build rule for target.
memory_piece_io_test/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/memory_piece_io_test.dir/build.make src/sorted_buffer/CMakeFiles/memory_piece_io_test.dir/build
.PHONY : memory_piece_io_test/fast

#=============================================================================
# Target rules for targets named sorted_buffer

# Build rule for target.
sorted_buffer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sorted_buffer
.PHONY : sorted_buffer

# fast build rule for target.
sorted_buffer/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/sorted_buffer.dir/build.make src/sorted_buffer/CMakeFiles/sorted_buffer.dir/build
.PHONY : sorted_buffer/fast

#=============================================================================
# Target rules for targets named sorted_buffer_iterator_test

# Build rule for target.
sorted_buffer_iterator_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sorted_buffer_iterator_test
.PHONY : sorted_buffer_iterator_test

# fast build rule for target.
sorted_buffer_iterator_test/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/sorted_buffer_iterator_test.dir/build.make src/sorted_buffer/CMakeFiles/sorted_buffer_iterator_test.dir/build
.PHONY : sorted_buffer_iterator_test/fast

#=============================================================================
# Target rules for targets named sorted_buffer_regression_test

# Build rule for target.
sorted_buffer_regression_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sorted_buffer_regression_test
.PHONY : sorted_buffer_regression_test

# fast build rule for target.
sorted_buffer_regression_test/fast:
	$(MAKE) -f src/sorted_buffer/CMakeFiles/sorted_buffer_regression_test.dir/build.make src/sorted_buffer/CMakeFiles/sorted_buffer_regression_test.dir/build
.PHONY : sorted_buffer_regression_test/fast

#=============================================================================
# Target rules for targets named signaling_queue_test

# Build rule for target.
signaling_queue_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 signaling_queue_test
.PHONY : signaling_queue_test

# fast build rule for target.
signaling_queue_test/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/signaling_queue_test.dir/build.make src/mapreduce_lite/CMakeFiles/signaling_queue_test.dir/build
.PHONY : signaling_queue_test/fast

#=============================================================================
# Target rules for targets named mapreduce_lite

# Build rule for target.
mapreduce_lite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mapreduce_lite
.PHONY : mapreduce_lite

# fast build rule for target.
mapreduce_lite/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/mapreduce_lite.dir/build.make src/mapreduce_lite/CMakeFiles/mapreduce_lite.dir/build
.PHONY : mapreduce_lite/fast

#=============================================================================
# Target rules for targets named utils_test

# Build rule for target.
utils_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils_test
.PHONY : utils_test

# fast build rule for target.
utils_test/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/utils_test.dir/build.make src/mapreduce_lite/CMakeFiles/utils_test.dir/build
.PHONY : utils_test/fast

#=============================================================================
# Target rules for targets named socket_communicator_test

# Build rule for target.
socket_communicator_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 socket_communicator_test
.PHONY : socket_communicator_test

# fast build rule for target.
socket_communicator_test/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/socket_communicator_test.dir/build.make src/mapreduce_lite/CMakeFiles/socket_communicator_test.dir/build
.PHONY : socket_communicator_test/fast

#=============================================================================
# Target rules for targets named protofile_test

# Build rule for target.
protofile_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protofile_test
.PHONY : protofile_test

# fast build rule for target.
protofile_test/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/protofile_test.dir/build.make src/mapreduce_lite/CMakeFiles/protofile_test.dir/build
.PHONY : protofile_test/fast

#=============================================================================
# Target rules for targets named tcp_socket_test

# Build rule for target.
tcp_socket_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcp_socket_test
.PHONY : tcp_socket_test

# fast build rule for target.
tcp_socket_test/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/tcp_socket_test.dir/build.make src/mapreduce_lite/CMakeFiles/tcp_socket_test.dir/build
.PHONY : tcp_socket_test/fast

#=============================================================================
# Target rules for targets named registerer_test

# Build rule for target.
registerer_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 registerer_test
.PHONY : registerer_test

# fast build rule for target.
registerer_test/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/registerer_test.dir/build.make src/mapreduce_lite/CMakeFiles/registerer_test.dir/build
.PHONY : registerer_test/fast

#=============================================================================
# Target rules for targets named reader_test

# Build rule for target.
reader_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reader_test
.PHONY : reader_test

# fast build rule for target.
reader_test/fast:
	$(MAKE) -f src/mapreduce_lite/CMakeFiles/reader_test.dir/build.make src/mapreduce_lite/CMakeFiles/reader_test.dir/build
.PHONY : reader_test/fast

#=============================================================================
# Target rules for targets named mrl-wordcount

# Build rule for target.
mrl-wordcount: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mrl-wordcount
.PHONY : mrl-wordcount

# fast build rule for target.
mrl-wordcount/fast:
	$(MAKE) -f src/mapreduce_lite/demo/CMakeFiles/mrl-wordcount.dir/build.make src/mapreduce_lite/demo/CMakeFiles/mrl-wordcount.dir/build
.PHONY : mrl-wordcount/fast

# Manual pre-install relink rule for target.
mrl-wordcount/preinstall:
	$(MAKE) -f src/mapreduce_lite/demo/CMakeFiles/mrl-wordcount.dir/build.make src/mapreduce_lite/demo/CMakeFiles/mrl-wordcount.dir/preinstall
.PHONY : mrl-wordcount/preinstall

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... varint32_test"
	@echo "... base"
	@echo "... class_register_test"
	@echo "... stl-util_test"
	@echo "... cvector_test"
	@echo "... strutil"
	@echo "... split_string_test"
	@echo "... strcodec_test"
	@echo "... join_strings_test"
	@echo "... stringprintf_test"
	@echo "... hash"
	@echo "... md5_hash_test"
	@echo "... system"
	@echo "... condition_variable_test"
	@echo "... mutex_test"
	@echo "... filepattern_test"
	@echo "... sorted_buffer_test"
	@echo "... memory_allocator_test"
	@echo "... memory_piece_test"
	@echo "... memory_piece_less_than_test"
	@echo "... memory_piece_io_test"
	@echo "... sorted_buffer"
	@echo "... sorted_buffer_iterator_test"
	@echo "... sorted_buffer_regression_test"
	@echo "... signaling_queue_test"
	@echo "... mapreduce_lite"
	@echo "... utils_test"
	@echo "... socket_communicator_test"
	@echo "... protofile_test"
	@echo "... tcp_socket_test"
	@echo "... registerer_test"
	@echo "... reader_test"
	@echo "... mrl-wordcount"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

